#@ load("app/refs.lib.yml", "resource_labels", "deployment_name")

#@ def hpa(props):
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: #@ props.name + "-hpa"
  labels: #@ resource_labels(props)
  #@ if/end props.namespace:
  namespace: #@ props.namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: #@ deployment_name(props)
  minReplicas: 1
  maxReplicas: 10
  #! alternatively ... targetCPUUtilizationPercentage
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
---
#! If you are not using kapp, this resource should be removed through overlays:
#!   #@overlay/match by=overlay.subset({"apiVersion": "kapp.k14s.io/v1alpha1", "kind": "Config"})
#!   #@overlay/remove
#!   ---
apiVersion: kapp.k14s.io/v1alpha1
kind: Config
rebaseRules:
- path: [spec, replicas]
  merge: copy
  #! Prefer HPA configured value from the cluster
  sources: [existing]
  resourceMatchers:
  - kindNamespaceNameMatcher:
      kind: Deployment
      #@ if/end props.namespace:
      namespace: #@ props.namespace
      name: #@ deployment_name(props)
#@ end
