#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")
#@ load("@ytt:base64", "base64")

apiVersion: v1
kind: Config

clusters:
- name: #@ data.values.cluster
  cluster:
    #@ if/end data.values.ca_cert:
    certificate-authority-data: #@ base64.encode(data.values.ca_cert)
    server: #@ "https://" + (data.values.address or assert.fail("missing address"))

users:
- name: #@ data.values.username
  user:
    username: #@ data.values.username or assert.fail("missing username")
    password: #@ data.values.password or assert.fail("missing password")

contexts:
- name: #@ data.values.context
  context:
    cluster: #@ data.values.cluster
    namespace: #@ data.values.namespace
    user: #@ data.values.username

current-context: #@ data.values.context
