#@ load("@ytt:template", "template")

#@ load("@github.com/k14s/k8s-lib:app/module.lib.yml", "app")

#@ port = 80

#@ def container():
image: hashicorp/http-echo
args:
- -listen=:(@= str(port) @)
- -text=$(cat /etc/text/string.txt)
volumeMounts:
- mountPath: /etc/text
  name: text-volume
#@ end

---
#@ def volumes():
- name: text-volume
  configMap:
    configMapName: hello2-text
#@ end

---
apiVersion: v1
kind: ConfigMap
stringData:
  string.txt: "hello from configmap!"

--- #@ template.replace(app.make("hello2", container(), port=port, replicas=10, volumes=volumes()).config())
