#@ load("@ytt:template", "template")

#@ load("@github.com/k14s/k8s-lib:app/module.lib.yml", "app")

#@ port = 80

#@ def container():
image: hashicorp/http-echo
args:
- #@ "-listen=:" + str(port)
- -text="hello!"
#@ end

--- #@ template.replace(app.make("hello", container(), port=port).config())
