#@ load("@ytt:template", "template")

#@ load("@github.com/k14s/k8s-lib:app/module.lib.yml", "app")

#@ hello_port = 80
#@ def hello_container():
image: nginx
args:
- -listen=:(@= str(hello_port) @)
- -text="hello!"
#@ end

--- #@ template.replace(app.make("hello", hello_container(), port=hello_port).config())
